name: PHPUnit

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Update package lists
        run: sudo apt-get update
      - name: Install Apache and required modules
        run: sudo apt-get install apache2 libapache2-mod-fcgid
      - name: test
        run: ls ~
      - name: Configure PHP-FPM
        run: |
          sudo cp ~/.phpenv/versions/$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")/etc/php-fpm.conf.default ~/.phpenv/versions/$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")/etc/php-fpm.conf
          sudo a2enmod rewrite actions fastcgi alias
          echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")/etc/php.ini
          sudo sed -i -e "s,www-data,runner,g" /etc/apache2/envvars
          sudo chown -R runner:runner /var/lib/apache2/fastcgi
          ~/.phpenv/versions/$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")/sbin/php-fpm
      - name: Copy config file
        run: cp tests/travis/config.php config.php
      - name: Composer update
        run: composer update
      - name: Composer install
        run: composer install
      - name: PHPUnit / PHP ${{ matrix.php-version }}
        run: composer test
